/**
 * Générateur G-code CNC générique.
 * Produit du G-code standard (Grbl / Mach3 / LinuxCNC compatible).
 */
export class GCodeGenerator {
  constructor(machine = {}) {
    this.machine = {
      feedrate:          machine.feedrate          ?? 1200,
      plungeRate:        machine.plungeRate        ?? 300,
      safeZ:             machine.safeZ             ?? 5,
      toolDiameter:      machine.toolDiameter      ?? 3.175,
      passes:            machine.passes            ?? 3,
      materialThickness: machine.materialThickness ?? 6,
      spindleSpeed:      machine.spindleSpeed      ?? 18000,
      depthPerPass:      machine.depthPerPass      ?? (machine.materialThickness ?? 6) / (machine.passes ?? 3),
      // Origine programme : appliquée à toutes les coordonnées émises
      originX: machine.originX ?? 0,  // décalage X (mm)
      originY: machine.originY ?? 0,  // décalage Y (mm)
      zOffset: machine.zOffset ?? 0,  // 0 = Z0 en surface, matThickness = Z0 en bas du brut
      unit: 'mm'
    };
    this.lines = [];
    this.stats = { totalLines: 0, estimatedTime: 0, totalDistance: 0 };
  }

  // ─── Primitives G-code ───────────────────────────────────────────────────

  emit(line) { this.lines.push(line); }

  header(title = 'BoxGenerator') {
    const { originX, originY, zOffset, toolDiameter, materialThickness, passes } = this.machine;
    const now = new Date().toISOString();
    this.emit(`; Generated by Box Generator — ${now}`);
    this.emit(`; Job: ${title}`);
    this.emit(`; Tool diameter: ${toolDiameter}mm`);
    const dpp         = this.machine.depthPerPass ?? (materialThickness / passes);
    const actualPasses = Math.max(1, Math.ceil(materialThickness / dpp));
    const stepZ        = materialThickness / actualPasses;
    const zList        = Array.from({ length: actualPasses }, (_, i) => `Z${-(stepZ * (i + 1)).toFixed(3)}`).join(', ');
    this.emit(`; Brut: ${materialThickness}mm | ${actualPasses} passe${actualPasses > 1 ? 's' : ''} × ${stepZ.toFixed(3)}mm`);
    this.emit(`; Passes: ${zList}`);
    this.emit(`; Origine XY: X${originX >= 0 ? '+' : ''}${originX.toFixed(3)} Y${originY >= 0 ? '+' : ''}${originY.toFixed(3)}`);
    this.emit(`; Origine Z: ${zOffset === 0 ? 'surface (haut)' : `bas du brut (+${zOffset.toFixed(3)}mm)`}`);
    this.emit('');
    this.emit('G21        ; Unités mm');
    this.emit('G90        ; Coordonnées absolues');
    this.emit('G17        ; Plan XY');
    this.emit(`S${this.machine.spindleSpeed} M3 ; Broche ON`);
    this.emit('G4 P2      ; Attente 2s démarrage broche');
    this.emit('');
  }

  footer() {
    this.emit('');
    this.emit('M5         ; Broche OFF');
    this.rapidZ(this.machine.safeZ);
    this.emit('G0 X0 Y0   ; Retour origine');
    this.emit('M30        ; Fin programme');
  }

  /**
   * Perce un trou en mode peck drilling.
   * Diametre effectif = diametre outil courant.
   */
  drillHole(x, y, depth, label, holeDia = null) {
    label = label || 'Trou de centrage';
    const dpp     = this.machine.depthPerPass;
    const passes  = Math.max(1, Math.ceil(depth / dpp));
    const stepZ   = depth / passes;
    const toolDia = this.machine.toolDiameter;
    const effDia  = holeDia ?? toolDia;

    const useHelix = holeDia && (holeDia - toolDia) > 0.5; // hélice seulement si écart > 0.5mm
    const strategy = useHelix ? 'hélice' : 'plongée';
    this.comment(`─── ${label} (${strategy}, Ø${(holeDia ?? this.machine.toolDiameter).toFixed(2)}mm, prof. ${depth}mm) ───`);
    this.rapidZ(this.machine.safeZ);

    if (!useHelix) {
      // Plongée directe
      this.rapidTo(x, y);
      for (let i = 1; i <= passes; i++) {
        this.plungeTo(-(stepZ * i));
        this.rapidZ(this.machine.safeZ);
      }
    } else {
      // Interpolation hélicoïdale (G2) — trou > outil
      const R  = (effDia - toolDia) / 2;
      const ox = this.machine.originX, oy = this.machine.originY;
      const zo = this.machine.zOffset;
      const f  = this.machine.feedrate;
      const sx = x + R; // point de départ sur le cercle (droite)

      this.rapidTo(sx, y);
      this.plungeTo(0);  // descente à la surface
      for (let i = 1; i <= passes; i++) {
        const z = (-(stepZ * i) + zo).toFixed(3);
        this.emit(`G2 X${(sx + ox).toFixed(3)} Y${(y + oy).toFixed(3)} I${(-R).toFixed(3)} J0.000 Z${z} F${f}`);
      }
      // Passe de finition à pleine profondeur (arc plat)
      this.emit(`G2 X${(sx + ox).toFixed(3)} Y${(y + oy).toFixed(3)} I${(-R).toFixed(3)} J0.000 F${f}`);
      this.rapidTo(x, y);
      this.rapidZ(this.machine.safeZ);
    }
  }

  rapidTo(x, y) {
    const ox = this.machine.originX, oy = this.machine.originY;
    this.emit(`G0 X${(x + ox).toFixed(3)} Y${(y + oy).toFixed(3)}`);
  }

  rapidZ(z) {
    this.emit(`G0 Z${(z + this.machine.zOffset).toFixed(3)}`);
  }

  lineTo(x, y, feedrate) {
    const f  = feedrate ?? this.machine.feedrate;
    const ox = this.machine.originX, oy = this.machine.originY;
    this.emit(`G1 X${(x + ox).toFixed(3)} Y${(y + oy).toFixed(3)} F${f}`);
  }

  plungeTo(z) {
    this.emit(`G1 Z${(z + this.machine.zOffset).toFixed(3)} F${this.machine.plungeRate}`);
  }

  comment(text) {
    this.emit(`; ${text}`);
  }

  // ─── Entrées outil ────────────────────────────────────────────────────────

  /**
   * Entrée en rampe linéaire (ramp-in).
   * L'outil descend progressivement de safeZ jusqu'à targetZ sur une longueur
   * égale à rampLen mm le long d'un segment aller-retour avant le point de départ.
   *
   * L'outil est déjà positionné en XY sur pts[0] à safeZ avant l'appel.
   * Après l'appel, l'outil est à pts[0] à targetZ, prêt pour le contour.
   *
   * @param {{x,y}[]} pts       - contour (pts[0] = point d'entrée)
   * @param {number}  targetZ   - profondeur de passe cible (négatif)
   * @param {number}  rampLen   - longueur de rampe en mm (défaut 1× diamètre outil)
   */
  _rampIn(pts, targetZ, rampLen) {
    const len = rampLen ?? this.machine.toolDiameter;
    // Direction du premier segment
    const dx = pts[1].x - pts[0].x;
    const dy = pts[1].y - pts[0].y;
    const segLen = Math.hypot(dx, dy) || 1;
    const ux = dx / segLen, uy = dy / segLen;

    // Clamp rampLen à la longueur du premier segment
    const rLen = Math.min(len, segLen * 0.9);

    const x1 = pts[0].x + ux * rLen;
    const y1 = pts[0].y + uy * rLen;

    this.comment('Ramp-in linéaire');
    // Aller : descend de 0 à targetZ sur rLen mm
    this.emit(`G1 X${(x1 + this.machine.originX).toFixed(3)} Y${(y1 + this.machine.originY).toFixed(3)} Z${(targetZ + this.machine.zOffset).toFixed(3)} F${this.machine.plungeRate}`);
    // Retour : reste à targetZ
    this.lineTo(pts[0].x, pts[0].y);
  }

  /**
   * Entrée hélicoïdale (helix-in).
   * Génère un arc hélicoïdal centré sur (cx, cy), rayon helixR,
   * descendant de safeZ jusqu'à targetZ sur `turns` tours.
   * Produit des G2/G3 arc en segments linéaires approchés.
   *
   * @param {number}  cx, cy   - centre de l'hélice
   * @param {number}  helixR   - rayon de l'hélice (mm)
   * @param {number}  targetZ  - profondeur cible (négatif)
   * @param {number}  turns    - nombre de tours (défaut 1)
   * @param {number}  segs     - segments par tour (défaut 36 = 10°)
   */
  _helixIn(cx, cy, helixR, targetZ, turns = 1, segs = 36) {
    const totalSteps = Math.round(turns * segs);
    const startZ = this.machine.safeZ;
    const ox = this.machine.originX, oy = this.machine.originY;

    this.comment(`Helix-in — R=${helixR.toFixed(2)}mm × ${turns} tour${turns > 1 ? 's' : ''}`);
    for (let i = 1; i <= totalSteps; i++) {
      const angle = -2 * Math.PI * (i / segs); // sens horaire (G2)
      const x = cx + helixR * Math.cos(angle);
      const y = cy + helixR * Math.sin(angle);
      const z = startZ + (targetZ - startZ) * (i / totalSteps);
      this.emit(`G1 X${(x + ox).toFixed(3)} Y${(y + oy).toFixed(3)} Z${(z + this.machine.zOffset).toFixed(3)} F${this.machine.plungeRate}`);
    }
    // Déplacer au point d'entrée du contour (bord de l'hélice)
  }

  /**
   * Calcule le point et la tangente d'entrée/sortie (lead-in/lead-out) sur un contour.
   * Retourne un arc de cercle tangent au premier segment.
   *
   * @param {{x,y}[]} pts      - contour (pts[0] = point d'entrée)
   * @param {number}  radius   - rayon de l'arc d'entrée (mm)
   * @param {'in'|'out'} type  - 'in' pour lead-in, 'out' pour lead-out
   * @returns {{arcPts: {x,y}[], entryPt: {x,y}}}
   */
  _leadArc(pts, radius, type) {
    const n = pts.length;
    const idx = type === 'in' ? 0 : n - 1;
    const next = type === 'in' ? pts[1] : pts[0];
    const curr = pts[idx];

    // Tangente au contour en pts[idx]
    const dx = next.x - curr.x, dy = next.y - curr.y;
    const tLen = Math.hypot(dx, dy) || 1;
    const tx = dx / tLen, ty = dy / tLen;

    // Normale (perpendiculaire, côté gauche = vers l'intérieur pour contour CCW)
    const nx = -ty, ny = tx;

    // Centre de l'arc = curr + normale × radius
    const cx = curr.x + nx * radius;
    const cy = curr.y + ny * radius;

    // Point d'approche (à 90° avant l'entrée)
    const approachPt = {
      x: cx - tx * radius,
      y: cy - ty * radius
    };

    // Arc de 90° de approachPt → curr, par segments linéaires
    const SEGS = 12;
    const a0 = Math.atan2(approachPt.y - cy, approachPt.x - cx);
    const a1 = Math.atan2(curr.y - cy, curr.x - cx);
    let dA = a1 - a0;
    // Choisir le sens qui correspond à une entrée tangentielle (arc court ≤ 180°)
    if (type === 'in') {
      if (dA > 0) dA -= 2 * Math.PI;  // sens anti-horaire → horaire
    } else {
      if (dA < 0) dA += 2 * Math.PI;
    }

    const arcPts = [];
    for (let i = 1; i <= SEGS; i++) {
      const a = a0 + dA * (i / SEGS);
      arcPts.push({ x: cx + radius * Math.cos(a), y: cy + radius * Math.sin(a) });
    }

    return { approachPt, arcPts };
  }

  // ─── Opérations de haut niveau ───────────────────────────────────────────

  /**
   * Fraise un profil fermé (liste de points) avec compensation d'outil.
   * @param {Array<{x,y}>} points  - contour fermé
   * @param {string}       side    - 'outside' | 'inside' | 'center'
   * @param {string}       label
   */
  /**
   * Fraise un profil fermé avec compensation d'outil, entrée progressive et lead-in/out.
   *
   * @param {Array<{x,y}>} points   - contour fermé
   * @param {string}       side     - 'outside' | 'inside' | 'center'
   * @param {Object}       entryOpts - options d'entrée
   *   entry   {'plunge'|'ramp'|'helix'} : mode d'entrée outil (défaut 'plunge')
   *   rampLen {number} : longueur rampe mm (défaut 1 × ⌀outil), pour 'ramp'
   *   helixR  {number} : rayon hélice mm (défaut 0.5 × ⌀outil), pour 'helix'
   *   helixTurns {number} : tours d'hélice (défaut 1)
   *   leadIn  {number|false} : rayon arc lead-in mm, false = désactivé (défaut false)
   *   leadOut {number|false} : rayon arc lead-out mm (défaut = leadIn)
   * @param {string}       label
   */
  cutContour(points, side = 'outside', entryOpts = {}, label = 'Contour') {
    if (points.length < 2) return;

    const entry      = entryOpts.entry      ?? 'plunge';
    const rampLen    = entryOpts.rampLen    ?? this.machine.toolDiameter;
    const helixR     = entryOpts.helixR     ?? this.machine.toolDiameter * 0.5;
    const helixTurns = entryOpts.helixTurns ?? 1;
    const leadInR    = entryOpts.leadIn     ?? false;
    const leadOutR   = entryOpts.leadOut    ?? leadInR;

    const offset = this._toolOffset(side);
    const pts    = offset !== 0 ? this._offsetContour(points, side) : points;
    const cPts   = entryOpts.dogbone ? this._insertDogbones(pts) : pts;

    const depth  = this.machine.materialThickness;
    const passes = Math.max(1, Math.ceil(depth / this.machine.depthPerPass));
    const stepZ  = depth / passes;

    const entryLabel = entry === 'ramp'  ? `, ramp ${rampLen}mm`
                     : entry === 'helix' ? `, helix R${helixR}mm×${helixTurns}t`
                     : '';
    const leadLabel  = leadInR ? `, lead-in R${leadInR}mm` : '';
    this.comment(`─── ${label} (${side}${entryLabel}${leadLabel}) ───`);

    // Lead-in : calcul du point d'approche si activé
    let leadIn  = leadInR  ? this._leadArc(pts, leadInR,  'in')  : null;
    let leadOut = leadOutR ? this._leadArc(pts, leadOutR, 'out') : null;

    for (let pass = 1; pass <= passes; pass++) {
      const z = -(stepZ * pass);
      this.comment(`Passe ${pass}/${passes} — Z=${z.toFixed(3)}`);
      this.rapidZ(this.machine.safeZ);

      if (entry === 'helix') {
        // ── Entrée hélicoïdale ──────────────────────────────────────────────
        // Centre de l'hélice = centroïde du contour
        const cx = pts.reduce((s, p) => s + p.x, 0) / pts.length;
        const cy = pts.reduce((s, p) => s + p.y, 0) / pts.length;
        this.rapidTo(cx + helixR, cy);
        this._helixIn(cx, cy, helixR, z, helixTurns);
        // Déplacement au point d'entrée (+ lead-in éventuel)
        if (leadIn) {
          this.rapidTo(leadIn.approachPt.x, leadIn.approachPt.y);
          leadIn.arcPts.forEach(p => this.lineTo(p.x, p.y));
        } else {
          this.rapidTo(cPts[0].x, cPts[0].y);
        }

      } else if (entry === 'ramp') {
        // ── Entrée en rampe ─────────────────────────────────────────────────
        this.rapidTo(cPts[0].x, cPts[0].y);
        this._rampIn(cPts, z, rampLen);
        if (leadIn) {
          this.rapidTo(leadIn.approachPt.x, leadIn.approachPt.y);
          leadIn.arcPts.forEach(p => this.lineTo(p.x, p.y));
        }

      } else {
        // ── Plongée directe (defaut) ─────────────────────────────────────────
        if (leadIn) {
          this.rapidTo(leadIn.approachPt.x, leadIn.approachPt.y);
          this.plungeTo(z);
          leadIn.arcPts.forEach(p => this.lineTo(p.x, p.y));
        } else {
          this.rapidTo(cPts[0].x, cPts[0].y);
          this.plungeTo(z);
        }
      }

      // ── Contour ─────────────────────────────────────────────────────────
      for (let i = 1; i < cPts.length; i++) this.lineTo(cPts[i].x, cPts[i].y);
      this.lineTo(cPts[0].x, cPts[0].y);

      // ── Lead-out ────────────────────────────────────────────────────────
      if (leadOut) {
        leadOut.arcPts.forEach(p => this.lineTo(p.x, p.y));
      }
    }

    this.rapidZ(this.machine.safeZ);
    this.comment('');
  }

  /**
   * Fraise plusieurs contours en interleaving les passes Z :
   * à chaque profondeur, tous les contours sont fraisés avant de descendre.
   * @param {Array<{x,y}[]>} contoursPoints - tableau de contours (points non offsettés)
   * @param {string} side - 'outside' | 'inside' | 'center'
   * @param {Object} entryOpts
   * @param {string} label
   */
  cutContoursInterleaved(contoursPoints, side = 'outside', label = 'Contour') {
    const offset = this._toolOffset(side);
    const allPts = contoursPoints
      .map(pts => offset !== 0 ? this._offsetContour(pts, side) : pts)
      .filter(pts => pts.length >= 2);
    if (allPts.length === 0) return;

    const depth  = this.machine.materialThickness;
    const passes = Math.max(1, Math.ceil(depth / this.machine.depthPerPass));
    const stepZ  = depth / passes;

    this.comment(`─── ${label} (${side}, ${allPts.length} anneaux fusionnés) ───`);

    for (let pass = 1; pass <= passes; pass++) {
      const z = -(stepZ * pass);
      this.comment(`Passe ${pass}/${passes} — Z=${z.toFixed(3)}`);
      for (const pts of allPts) {
        this.rapidZ(this.machine.safeZ);
        this.rapidTo(pts[0].x, pts[0].y);
        this.plungeTo(z);
        for (let i = 1; i < pts.length; i++) this.lineTo(pts[i].x, pts[i].y);
        this.lineTo(pts[0].x, pts[0].y);
      }
    }

    this.rapidZ(this.machine.safeZ);
    this.comment('');
  }

  /**
   * Fraise un contour fermé avec tabs (ponts de maintien).
   *
   * Les tabs sont répartis uniformément sur le périmètre.
   * Sur les passes intermédiaires, le contour est fraisé normalement.
   * Sur la dernière passe, l'outil remonte à tabZ au passage de chaque tab.
   *
   * @param {Array<{x,y}>} points   - contour fermé (non offsetté)
   * @param {string}       side     - 'outside' | 'inside' | 'center'
   * @param {Object}       tabOpts  - options des tabs
   *   count  {number} : nombre de tabs (défaut 4)
   *   width  {number} : largeur d'un tab en mm (défaut 4)
   *   height {number} : hauteur résiduelle du tab en mm (défaut 1.5)
   * @param {string}       label
   */
  /**
   * Identique à cutContour mais avec tabs sur la dernière passe.
   * Accepte les mêmes entryOpts que cutContour.
   */
  cutContourWithTabs(points, side = 'outside', tabOpts = {}, entryOpts = {}, label = 'Contour (tabs)') {
    if (points.length < 2) return;

    const tabCount  = tabOpts.count  ?? 4;
    const tabWidth  = tabOpts.width  ?? 4;
    const tabHeight = tabOpts.height ?? 1.5;

    const offset  = this._toolOffset(side);
    const rawPts  = offset !== 0 ? this._offsetContour(points, side) : points;
    const pts     = entryOpts.dogbone ? this._insertDogbones(rawPts) : rawPts;

    const depth  = this.machine.materialThickness;
    const passes = Math.max(1, Math.ceil(depth / this.machine.depthPerPass));
    const stepZ  = depth / passes;
    // Z de la surface supérieure des tabs (matière résiduelle non coupée)
    const tabZ   = -(depth - tabHeight);

    // ── Longueurs cumulées des segments ─────────────────────────────────────
    const n = pts.length;
    const segLengths = [];
    let perimeter = 0;
    for (let i = 0; i < n; i++) {
      const a   = pts[i];
      const b   = pts[(i + 1) % n];
      const len = Math.hypot(b.x - a.x, b.y - a.y);
      segLengths.push(len);
      perimeter += len;
    }

    // ── Positions curvilignes des centres de tabs ────────────────────────────
    // Répartition uniforme, premier tab à la moitié de l'intervalle
    const tabCenters = [];
    for (let t = 0; t < tabCount; t++) {
      tabCenters.push((perimeter / tabCount) * (t + 0.5));
    }

    // ── Placement des tabs aux milieux des segments droits ───────────────────
    // Au lieu d'une distribution uniforme + filtrage (qui place des tabs sur des
    // angles quand les positions tombent sur des transitions), on identifie tous
    // les segments droits (entre coins consécutifs) et on place chaque tab au
    // milieu du segment le plus long disponible. Fonctionne pour les contours
    // simples (rectangle) comme pour les finger-joints (nombreux coins 90°).
    const CORNER_THR  = 20;              // degrés — au-delà : coin réel
    const cornerMargin = tabWidth / 2 + 2; // marge bord-de-tab → coin (mm)

    // Recenser tous les coins (toutes directions confondues)
    const allCornerDists = [];
    {
      let cd = 0;
      for (let i = 0; i < n; i++) {
        const prev = pts[(i - 1 + n) % n], curr = pts[i], next = pts[(i + 1) % n];
        const d1x = curr.x - prev.x, d1y = curr.y - prev.y;
        const d2x = next.x - curr.x, d2y = next.y - curr.y;
        const l1  = Math.hypot(d1x, d1y) || 1, l2 = Math.hypot(d2x, d2y) || 1;
        const cosA = Math.max(-1, Math.min(1, (d1x/l1)*(d2x/l2) + (d1y/l1)*(d2y/l2)));
        if (Math.acos(cosA) * 180 / Math.PI > CORNER_THR) allCornerDists.push(cd);
        cd += segLengths[i];
      }
    }

    // Construire la liste des segments droits entre coins consécutifs
    // et placer un tab au milieu de chacun des N plus longs
    let safeTabCenters;
    const nc = allCornerDists.length;
    if (nc === 0) {
      // Forme sans coins (cercle, ovale) : répartition uniforme classique
      safeTabCenters = tabCenters;
    } else {
      const sorted = [...allCornerDists].sort((a, b) => a - b);
      const segs = [];
      for (let i = 0; i < nc; i++) {
        const s   = sorted[i];
        const e   = i + 1 < nc ? sorted[i + 1] : sorted[0] + perimeter;
        const len = e - s;
        if (len > tabWidth + cornerMargin)
          segs.push({ center: ((s + e) / 2) % perimeter, len });
      }
      // Algorithme farthest-first : commence sur le segment le plus long,
      // puis choisit à chaque étape le segment dont le centre est le plus
      // éloigné de tous les tabs déjà placés → répartition maximale
      // indépendamment du point de départ du contour.
      segs.sort((a, b) => b.len - a.len); // tri par longueur décroissante
      safeTabCenters = [];
      const used = new Array(segs.length).fill(false);
      if (segs.length > 0) {
        safeTabCenters.push(segs[0].center);
        used[0] = true;
      }
      while (safeTabCenters.length < tabCount) {
        let best = -1, bestMinDist = -1;
        for (let i = 0; i < segs.length; i++) {
          if (used[i]) continue;
          const c = segs[i].center;
          const minDist = Math.min(...safeTabCenters.map(placed => {
            const d = Math.abs(c - placed);
            return Math.min(d, perimeter - d);
          }));
          if (minDist > bestMinDist) { bestMinDist = minDist; best = i; }
        }
        if (best < 0) break;
        safeTabCenters.push(segs[best].center);
        used[best] = true;
      }
    }
    const skippedTabs = tabCount - safeTabCenters.length;

    const entry      = entryOpts.entry      ?? 'plunge';
    const rampLen    = entryOpts.rampLen    ?? this.machine.toolDiameter;
    const helixR     = entryOpts.helixR     ?? this.machine.toolDiameter * 0.5;
    const helixTurns = entryOpts.helixTurns ?? 1;

    this.comment(`─── ${label} (${side}, ${safeTabCenters.length} tabs ${tabWidth}×${tabHeight}mm${skippedTabs ? `, ${skippedTabs} évité(s) sur angles` : ''}) ───`);

    for (let pass = 1; pass <= passes; pass++) {
      const z        = -(stepZ * pass);
      const lastPass = pass === passes;

      this.comment(`Passe ${pass}/${passes} — Z=${z.toFixed(3)}${lastPass ? ' [tabs actifs]' : ''}`);
      this.rapidZ(this.machine.safeZ);

      // ── Entrée outil ───────────────────────────────────────────────────
      if (entry === 'helix') {
        const cx = pts.reduce((s, p) => s + p.x, 0) / pts.length;
        const cy = pts.reduce((s, p) => s + p.y, 0) / pts.length;
        this.rapidTo(cx + helixR, cy);
        this._helixIn(cx, cy, helixR, z, helixTurns);
        this.rapidTo(pts[0].x, pts[0].y);
      } else if (entry === 'ramp') {
        this.rapidTo(pts[0].x, pts[0].y);
        this._rampIn(pts, z, rampLen);
      } else {
        this.rapidTo(pts[0].x, pts[0].y);
        this.plungeTo(z);
      }

      if (!lastPass) {
        // Passes intermédiaires : contour normal
        for (let i = 1; i < n; i++) this.lineTo(pts[i].x, pts[i].y);
        this.lineTo(pts[0].x, pts[0].y);
      } else {
        // Dernière passe : tabs positionnés sur le chemin curviligne global.
        // Fonctionne pour toute forme, y compris les cercles/ovales dont les
        // segments individuels sont plus courts que la largeur d'un tab.

        // Événements de changement de Z triés par distance curviligne :
        // 'up' = début du tab (monte à tabZ), 'down' = fin du tab (replonge à z)
        const zEvents = [];
        for (const center of safeTabCenters) {
          const s = Math.max(0, center - tabWidth / 2);
          const e = Math.min(perimeter - 1e-6, center + tabWidth / 2);
          zEvents.push({ dist: s, action: 'up'   });
          zEvents.push({ dist: e, action: 'down' });
        }
        zEvents.sort((a, b) => a.dist - b.dist);

        let cumDist = 0;
        let evIdx   = 0;

        for (let i = 0; i < n; i++) {
          const a   = pts[i];
          const b   = pts[(i + 1) % n];
          const len = segLengths[i];
          if (len < 1e-6) { cumDist += len; continue; }
          const dx = (b.x - a.x) / len;
          const dy = (b.y - a.y) / len;
          const segEnd = cumDist + len;

          // Traiter tous les événements Z dont la position tombe dans ce segment
          while (evIdx < zEvents.length && zEvents[evIdx].dist < segEnd) {
            const ev = zEvents[evIdx++];
            const t  = (ev.dist - cumDist) / len;
            this.lineTo(a.x + dx * t * len, a.y + dy * t * len);
            if (ev.action === 'up') {
              this.rapidZ(tabZ);
            } else {
              this.plungeTo(z);
            }
          }

          this.lineTo(b.x, b.y);
          cumDist += len;
        }
        this.lineTo(pts[0].x, pts[0].y); // fermeture du contour
      }
    }

    this.rapidZ(this.machine.safeZ);
    this.comment('');
  }

  /**
   * Pocket d'une forme quelconque par balayage raster (zig-zag).
   * Compense le rayon d'outil par insetting du contour.
   *
   * Entre deux lignes raster consécutives, l'outil se dégage à `clearance` mm
   * au-dessus du fond de passe (et non au safeZ) pour éviter les ~N retracts
   * inutiles. Un retrait complet au safeZ n'est fait que pour les tronçons
   * non-contigus sur la même ligne Y (formes concaves).
   *
   * @param {Array<{x,y}>} points  - contour fermé de la poche
   * @param {string}       label
   */
  pocketShape(points, label = 'Pocket', depthStart = 0) {
    if (points.length < 3) return;

    const td          = this.machine.toolDiameter;
    const r           = td / 2;
    const overlap     = 0.4;
    const stepOver    = td * (1 - overlap);
    const remainDepth = this.machine.materialThickness - depthStart;
    const passes      = Math.max(1, Math.ceil(remainDepth / this.machine.depthPerPass));
    const stepZ       = remainDepth / passes;
    const clearance = 1.0;  // dégagement inter-lignes au-dessus du fond de passe (mm)

    // Bounding box de la zone fraisable (inset d'un rayon d'outil)
    const allX = points.map(p => p.x);
    const allY = points.map(p => p.y);
    const minX = Math.min(...allX) + r;
    const maxX = Math.max(...allX) - r;
    const minY = Math.min(...allY) + r;
    const maxY = Math.max(...allY) - r;

    if (minX >= maxX || minY >= maxY) {
      this.comment(`ATTENTION: forme trop petite pour l'outil (${td}mm)`);
      return;
    }

    this.comment(`─── ${label} — Pocket raster ───`);

    for (let pass = 1; pass <= passes; pass++) {
      const z      = -(depthStart + stepZ * pass);
      const clearZ = z + clearance;  // niveau de dégagement inter-lignes
      this.comment(`Passe ${pass}/${passes} — Z=${z.toFixed(3)}`);
      this.rapidZ(this.machine.safeZ);

      let curY      = minY;
      let dir       = 1;
      let firstMove = true;

      while (curY <= maxY + 1e-6) {
        // Intersections de la ligne horizontale avec le contour
        const xCuts = this._rasterIntersections(points, curY);
        if (xCuts.length >= 2) {
          xCuts.sort((a, b) => a - b);
          let firstSegInRow = true;
          // Traite chaque paire d'intersections (gestion des formes concaves)
          for (let k = 0; k + 1 < xCuts.length; k += 2) {
            const xFrom_raw = xCuts[k]     + r;
            const xTo_raw   = xCuts[k + 1] - r;
            if (xTo_raw <= xFrom_raw) continue;

            const xFrom = dir > 0 ? xFrom_raw : xTo_raw;
            const xTo   = dir > 0 ? xTo_raw   : xFrom_raw;

            if (firstMove) {
              // Première plongée de la passe
              this.rapidTo(xFrom, curY);
              if (depthStart > 0) this.emit(`G0 Z${(-depthStart + this.machine.zOffset).toFixed(3)}`);
              this.plungeTo(z);
              firstMove = false;
            } else if (!firstSegInRow) {
              // Même ligne Y, tronçon non-contigu (forme concave) → retrait complet
              this.rapidZ(this.machine.safeZ);
              this.rapidTo(xFrom, curY);
              if (depthStart > 0) this.emit(`G0 Z${(-depthStart + this.machine.zOffset).toFixed(3)}`);
              this.plungeTo(z);
            } else {
              // Nouvelle ligne raster → dégagement minimal (sans retour au safeZ)
              this.emit(`G0 Z${(clearZ + this.machine.zOffset).toFixed(3)}`);
              this.rapidTo(xFrom, curY);
              this.plungeTo(z);
            }
            this.lineTo(xTo, curY);
            firstSegInRow = false;
          }
        }

        curY += stepOver;
        dir  *= -1;
      }

      this.rapidZ(this.machine.safeZ);
    }
    this.comment('');
  }

  /**
   * Pocket rectangulaire (raster zig-zag).
   */
  pocketRectangle(x, y, w, h, label = 'Pocket') {
    const td       = this.machine.toolDiameter;
    const overlap  = 0.4;
    const stepOver = td * (1 - overlap);
    const depth    = this.machine.materialThickness;
    const passes   = Math.max(1, Math.ceil(depth / this.machine.depthPerPass));
    const stepZ    = depth / passes;

    this.comment(`─── ${label} — Pocket ${w.toFixed(1)}×${h.toFixed(1)}mm ───`);

    for (let pass = 1; pass <= passes; pass++) {
      const z = -(stepZ * pass);
      this.comment(`Passe ${pass}/${passes} — Z=${z.toFixed(3)}`);
      this.rapidZ(this.machine.safeZ);

      let curY = y + td / 2;
      let dir  = 1;
      this.rapidTo(x + td / 2, curY);
      this.plungeTo(z);

      while (curY <= y + h - td / 2) {
        const x1 = dir > 0 ? x + w - td / 2 : x + td / 2;
        this.lineTo(x1, curY);
        curY += stepOver;
        if (curY <= y + h - td / 2) this.lineTo(x1, curY);
        dir *= -1;
      }
      this.rapidZ(this.machine.safeZ);
    }
    this.comment('');
  }

  // ─── Utilitaires ─────────────────────────────────────────────────────────

  _toolOffset(side) {
    const r = this.machine.toolDiameter / 2;
    if (side === 'outside') return  r;
    if (side === 'inside')  return -r;
    return 0;
  }

  /**
   * Insète un contour fermé de d mm vers l'intérieur.
   * Utilisé par les modules de boîte pour les poches et feuillures
   * afin que l'outil suive les rayons de coin de la forme.
   */
  insetContour(points, d) {
    return this._offsetContourDist(points, d);  // +d : normale gauche pointe vers l'intérieur (contours CW en coords écran)
  }

  /**
   * Post-traitement du chemin d'outil offsetté : insère un mouvement T-bone
   * à chaque coin intérieur (concave) pour permettre l'emboîtement des encoches.
   *
   * À chaque coin détecté (produit vectoriel < -seuil), l'outil avance de r mm
   * au-delà du coin dans la direction d'arrivée, puis revient au coin.
   * Cela creuse un keyhole qui libère les coins carrés des tenons.
   */
  _insertDogbones(pts) {
    const r = this.machine.toolDiameter / 2;
    if (pts.length < 3 || r <= 0) return pts;
    const result = [];
    const n = pts.length;
    // Facteur de déplacement : le centre du dogbone est à r*(√2−1) du coin offsetté
    // dans la direction de la bisectrice des normales gauches, ce qui le place
    // exactement à distance r du coin original (tangente = angle droit).
    const scale = r * (Math.SQRT2 - 1);
    for (let i = 0; i < n; i++) {
      const prev = pts[(i - 1 + n) % n];
      const curr = pts[i];
      const next = pts[(i + 1) % n];
      const dx1 = curr.x - prev.x, dy1 = curr.y - prev.y;
      const dx2 = next.x - curr.x, dy2 = next.y - curr.y;
      const len1 = Math.hypot(dx1, dy1) || 1;
      const len2 = Math.hypot(dx2, dy2) || 1;
      const v1x = dx1 / len1, v1y = dy1 / len1;
      const v2x = dx2 / len2, v2y = dy2 / len2;
      // Produit vectoriel : < 0 = virage intérieur (coin concave) en coords écran Y↓
      const cross = v1x * v2y - v1y * v2x;
      if (cross < -0.5) {
        // Bisectrice des normales gauches (même formule que _offsetContourDist)
        let bx = -v1y + -v2y, by = v1x + v2x;
        const bl = Math.hypot(bx, by) || 1;
        bx /= bl; by /= bl;
        // Centre du dogbone : décalé de r*(√2−1) dans la direction de la bisectrice
        // → distance exacte r du coin original
        result.push(curr);
        result.push({ x: curr.x + scale * bx, y: curr.y + scale * by });
        result.push(curr);
      } else {
        result.push(curr);
      }
    }
    return result;
  }

  /**
   * Décale un contour fermé vers l'extérieur (outside) ou l'intérieur (inside)
   * d'un rayon d'outil (compensation d'outil).
   */
  _offsetContour(points, side) {
    const r    = this.machine.toolDiameter / 2;
    const sign = side === 'outside' ? -1 : 1;  // -r : s'éloigne de la normale intérieure (vers l'ext.)
    return this._offsetContourDist(points, sign * r);
  }

  /**
   * Décale un contour fermé par bisectrice normalisée (direction = normale gauche).
   * Pour les contours CW en coordonnées écran (Y bas) : dist > 0 = vers l'intérieur,
   * dist < 0 = vers l'extérieur.
   */
  _offsetContourDist(points, dist) {
    // Supprimer les points dupliqués / quasi-identiques (évite bisecteurs dégénérés)
    let pts = [points[0]];
    for (let i = 1; i < points.length; i++) {
      if (Math.hypot(points[i].x - pts[pts.length - 1].x, points[i].y - pts[pts.length - 1].y) > 1e-6)
        pts.push(points[i]);
    }
    // Supprimer le dernier point s'il est identique au premier (contour fermé avec doublon)
    while (pts.length > 1 && Math.hypot(pts[pts.length - 1].x - pts[0].x, pts[pts.length - 1].y - pts[0].y) < 1e-6)
      pts.pop();

    const n      = pts.length;
    const result = [];

    for (let i = 0; i < n; i++) {
      const prev = pts[(i - 1 + n) % n];
      const curr = pts[i];
      const next = pts[(i + 1) % n];

      const t1x  = curr.x - prev.x, t1y = curr.y - prev.y;
      const t2x  = next.x - curr.x, t2y = next.y - curr.y;
      const len1 = Math.hypot(t1x, t1y) || 1e-9;
      const len2 = Math.hypot(t2x, t2y) || 1e-9;

      const n1x = -t1y / len1, n1y = t1x / len1;
      const n2x = -t2y / len2, n2y = t2x / len2;

      let bx = n1x + n2x, by = n1y + n2y;
      const blen = Math.hypot(bx, by) || 1;
      bx /= blen; by /= blen;

      const dot          = n1x * bx + n1y * by;
      const miter        = dot !== 0 ? 1 / dot : 1;
      const clampedMiter = Math.min(miter, 3);

      result.push({
        x: curr.x + dist * clampedMiter * bx,
        y: curr.y + dist * clampedMiter * by
      });
    }
    return result;
  }

  /**
   * Calcule les abscisses X d'intersection d'une ligne Y=y avec le contour.
   * Algorithme ray-casting classique.
   */
  _rasterIntersections(points, y) {
    const n  = points.length;
    const xs = [];
    for (let i = 0; i < n; i++) {
      const a = points[i];
      const b = points[(i + 1) % n];
      if ((a.y <= y && b.y > y) || (b.y <= y && a.y > y)) {
        const t = (y - a.y) / (b.y - a.y);
        xs.push(a.x + t * (b.x - a.x));
      }
    }
    return xs;
  }

  getCode() {
    return this.lines.join('\n');
  }

  getStats() {
    const lineCount = this.lines.length;
    let dist = 0;
    let lastX = 0, lastY = 0, lastZ = 0;
    for (const line of this.lines) {
      const xm = line.match(/X([-\d.]+)/);
      const ym = line.match(/Y([-\d.]+)/);
      const zm = line.match(/Z([-\d.]+)/);
      const x  = xm ? parseFloat(xm[1]) : lastX;
      const y  = ym ? parseFloat(ym[1]) : lastY;
      const z  = zm ? parseFloat(zm[1]) : lastZ;
      if (line.startsWith('G1')) {
        dist += Math.hypot(x - lastX, y - lastY, z - lastZ);
      }
      lastX = x; lastY = y; lastZ = z;
    }
    const timeMin = dist / this.machine.feedrate;
    return {
      lines:    lineCount,
      distance: dist.toFixed(0),
      timeMin:  timeMin.toFixed(1)
    };
  }
}